### ISSUE TITLE
Issue with remove button

### ISSUE THREAD

**Issue by pbanigo** [pbanigo/library#1]
At times remove button doesn't work

**Comment by nitin094-hub** [comment]
Could you assign this issue to me?

**Comment by pbanigo** [comment]
> Could you assign this issue to me?

Done!

**Comment by nitin094-hub** [comment]
I think the remove button works perfectly.

**Comment by pbanigo** [comment]
I noticed if I add maybe 5 items then start removing them randomly, at a point it removes the items from the page but not from the Library so when I refresh they return.

**Comment by pbanigo** [comment]
Created Unique Id's for each object then used Array.filter to Target it. With Array.splice which was used before, whenever an item is removed from the array, the array index changes so after the first delete, practically everything getting deleted is wrong on the Array level. The issue was coming up when trying to delete index numbers referenced but no longer in the Array.
